schemaVersion: 2.2.0
metadata:
  name: dw-demo
components:
  - name: devtools
    container:
      image: "quay.io/devfile/universal-developer-image:ubi8-latest"
      memoryLimit: 2Gi
      memoryRequest: 256Mi
commands:
  - id: 0-prep01-deploy-editors
    exec:
      commandLine: 'kubectl apply -f ./editors-contributions/'
      component: devtools
