kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: microservices-demo
  namespace: dw-demo
spec:
  started: true
  # Commenting out, waiting for https://github.com/devfile/devworkspace-operator/pull/868
  # pods:
  #   metadata:
  #     annotations:
  #       io.openshift.userns: "true"
  #       io.kubernetes.cri-o.userns-mode: "auto:size=65536;map-to-root=true"  # <-- user namespace
  contributions:
    - name: editor
      kubernetes:
        name: ttyd
  template:
    attributes:
      controller.devfile.io/storage-type: ephemeral
    projects:
      - name: microservices-demo-frontend
        git:
          remotes:
            origin: "https://github.com/l0rd/microservices-demo-frontend"
    components:
      - name: frontend
        attributes:
          controller.devfile.io/merge-contribution: true
        container:
          image: quay.io/mloriedo/universal-developer-image:ubi8-dw-demo
