kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: microservices-demo
  namespace: dw-demo
spec:
  started: true
  # routingClass: che
  contributions:
    - name: editor
      plugin:
        kubernetes:
          name: ttyd
  template:
    attributes:
      controller.devfile.io/storage-type: ephemeral
    projects:
      - name: microservices-demo-frontend
        git:
          remotes:
            origin: "https://github.com/l0rd/microservices-demo-frontend"
    components:
      - name: frontend
        attributes:
          controller.devfile.io/merge-contribution: true
        container:
          image: quay.io/mloriedo/universal-developer-image:ubi8-dw-demo
      - name: catalogue
        container:
          image: weaveworksdemos/catalogue:0.3.5
          cpuLimit: 200m
          memoryLimit: 200Mi
          cpuRequest: 100m
          memoryRequest: 100Mi
          command:
            - sh
          args:
            - '-c'
            - 'tail -f /dev/null'
            # - 'sleep 30 && /app -port 8080 -DSN "catalogue_user:default_password@tcp(catalogue-db:3306)/socksdb"'
            # - 'sleep 30 && /app -port 8080 -DSN "catalogue_user:default_password@tcp(localhost:3306)/socksdb"'
          endpoints:
            - name: catalogue
              targetPort: 8080
              exposure: internal
      - name: catalogue-db
        container:
          image: weaveworksdemos/catalogue-db:0.3.0
          cpuLimit: 200m
          memoryLimit: 300Mi
          cpuRequest: 100m
          memoryRequest: 100Mi
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: fake_password
          - name: MYSQL_DATABASE
            value: socksdb
          volumeMounts:
            - name: catalogue-volume
              path: /var/lib/mysql
          endpoints:
            - name: catalogue-db
              targetPort: 3360
              exposure: internal
      - name: catalogue-volume
        volume:
          ephemeral: true
    commands:
      - id: install
        exec:
          component: frontend
          commandLine: npm install
      - id: container-build
        exec:
          component: frontend
          commandLine: buildah
