kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: dw
spec:
  started: true
  template:
    attributes:
      controller.devfile.io/storage-type: ephemeral
    projects:
      - name: quarkus-api
        git:
          remotes:
            origin: https://github.com/l0rd/quarkus-api
    components:
      - name: dev-tooling
        container:
          image: quay.io/mloriedo/devtools:latest
          memoryRequest: 2G
          memoryLimit: 10G
          cpuRequest: '1'
          cpuLimit: '4'
      - name: postgresql
        container:
          image: 'quay.io/centos7/postgresql-13-centos7@sha256:994f5c622e2913bda1c4a7fa3b0c7e7f75e7caa3ac66ff1ed70ccfe65c40dd75'
          env:
            - name: POSTGRESQL_USER
              value: user
            - name: POSTGRESQL_PASSWORD
              value: password
            - name: POSTGRESQL_DATABASE
              value: food_db
            - name: PGDATA
              value: /tmp/pgdata
    commands:
      - id: 1-package
        exec:
          component: dev-tooling
          commandLine: './mvnw clean package -DskipTests=true -Dquarkus.profile=staging'
      - id: 2-runtests
        exec:
          component: dev-tooling
          commandLine: './mvnw test'
  contributions:
    - name: editor
      kubernetes:
        name: vscode

